/** Never reflect unexpected database/provider messages to the browser. */
export function apiErrorDetails(error: unknown) {
  const candidate = error instanceof Error ? error.message : "";
  const statuses: Record<string, number> = {
    AUTH_REQUIRED: 401, ACTIVE_TENANT_REQUIRED: 403, TENANT_ACCESS_DENIED: 403,
    ROLE_NOT_ALLOWED: 403, ORIGIN_NOT_ALLOWED: 403,
    TRUSTED_CONTEXT_INVALID: 400, TRUSTED_CONTEXT_DENIED: 403,
    TRUSTED_CONTACT_SCOPE_DENIED: 403, COMPANY_TENANT_MISMATCH: 409,
    MEMBERSHIP_MANAGEMENT_DENIED: 403, MEMBER_NOT_FOUND: 404,
    LAST_OWNER_REQUIRED: 409, MEMBER_ALREADY_EXISTS: 409, INVITATION_FAILED: 502,
    RATE_LIMIT_EXCEEDED: 429, RATE_LIMIT_CHECK_FAILED: 503,
    UPLOAD_FILE_REJECTED: 422, UPLOAD_SESSION_INVALID: 409,
    STORAGE_QUOTA_EXCEEDED: 429, UPLOAD_TARGET_FAILED: 500,
    INVALID_JSON: 400, JSON_CONTENT_TYPE_REQUIRED: 415, REQUEST_TOO_LARGE: 413,
    INVALID_IDENTIFIER: 400,
    DIAGNOSTIC_NOT_FOUND: 404, COMPANY_NOT_FOUND: 404,
    DIAGNOSTIC_CHANGED: 409, DIAGNOSTIC_NOT_EDITABLE: 409,
    LEGACY_DIAGNOSTIC_REASSESSMENT_REQUIRED: 409,
    DIAGNOSTIC_PATH_INCOMPLETE: 422, INSUFFICIENT_COVERAGE: 422,
    EVIDENCE_REFERENCE_NOT_AVAILABLE: 422,
    MATURITY_REQUIRED_FOR_SCORE_ANCHOR: 422, NOT_APPLICABLE_NOT_ALLOWED: 422,
    INVALID_ANSWER_STATE: 422, QUESTION_NOT_IN_ACTIVE_PATH: 409, UNKNOWN_QUESTION: 400,
  };
  return candidate in statuses
    ? { code: candidate, status: statuses[candidate] }
    : { code: "INTERNAL_ERROR", status: 500 };
}

export function assertUuid(value: string): void {
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) {
    throw new Error("INVALID_IDENTIFIER");
  }
}
