export {
  questionBank,
  starterQuestions,
  scoreAnchorQuestions,
  diagnosticQueue,
  selectAdaptiveQuestions,
  questionMetadata,
  DiagnosticStages,
  DiagnosticStrategyVersion,
  CoreScoreQuestionIds,
  StarterQuestionIds,
  type DiagnosticProfile,
  type DiagnosticQuestion,
  type AnswerState,
  type StrategyAnswer,
  type ApplicabilityContext,
} from "./diagnostic-strategy";

import {
  starterQuestions,
  type DiagnosticProfile,
} from "./diagnostic-strategy";

export const ESSENTIAL_TARGET_MIN = 31;
export const ESSENTIAL_TARGET_MAX = 42;

export function selectDiagnosticQuestions(profile: DiagnosticProfile) {
  // Compatibility: this returns the non-adaptive starting set.
  // Runtime question flow is generated by diagnosticQueue().
  void profile;
  return starterQuestions();
}

export function diagnosticCoverage(
  _profile: DiagnosticProfile,
  answeredIds: string[],
) {
  const questions = starterQuestions();
  const done = new Set(answeredIds);
  return questions.length
    ? questions.filter((question) => done.has(question.id)).length /
        questions.length
    : 0;
}
